version: '3.8'

services:
  example-backend:
    image: example-backend
    build: "../../part1/14/backend"
    container_name: example-backend
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis-db
  
  example-frontend:
    image: example-frontend
    build: "../../part1/14/frontend"
    container_name: example-frontend
    ports:
      - "5000:5000"
  
  redis:
    image: redis
    container_name: redis-db
    ports:
      - "6379:6379"