version: '3.8'

services:
  example-backend:
    image: example-backend
    build: "../../part1/14/backend"
    container_name: example-backend
    ports:
      - "8080:8080"
  
  example-frontend:
    image: example-frontend
    build: "../../part1/14/frontend"
    container_name: example-frontend
    ports:
      - "5000:5000"